image: computermouth/sudeb

variables:
  DEBIAN_FRONTEND: noninteractive
  LANG: C

before_script:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -y wine wine32 git wget debconf
  - ./keyboard_set.sh 
  - sudo apt-get install -y xserver-xorg-video-dummy
  - sudo apt-get install -y xinit

setup:
  script:
    - mkdir -p ../dupe
    - cp -r * ../dupe
    - wget https://github.com/git-for-windows/build-extra/releases/download/git-sdk-1.0.3/git-sdk-installer-1.0.3-64.7z.exe
    - sudo startx&
    - sleep 10s
    - wine git-*.exe -y -gm2
    - ls -lsah
