stages:
  - build

job:
  stage: build
  tags: [onsite-win10-001]
  script:
     - set PATH=%PATH%;C:/git-sdk-64/mingw64/bin;C:/git-sdk-64/usr/bin& set MSYSTEM=MINGW64& set MSYS2_PATH_TYPE=inherit
     - C:/git-sdk-64/usr/bin/bash -c "echo $SHELL"
     - set PATH=%PATH%;C:/git-sdk-64/mingw64/bin;C:/git-sdk-64/usr/bin& set MSYSTEM=MSYS2& set MSYS2_PATH_TYPE=inherit
     - C:/git-sdk-64/usr/bin/bash -c "echo $PWD"
