image: computermouth/sudeb

variables:
  DEBIAN_FRONTEND: noninteractive
  LANG: C

before_script:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - echo 'XKBMODEL="pc105"' | sudo tee /etc/default/keyboard
  - echo 'XKBLAYOUT="us"' | sudo tee -a /etc/default/keyboard
  - echo 'XKBVARIANT=""' | sudo tee -a /etc/default/keyboard
  - echo 'XKBOPTIONS="grp:alt_shift_toggle"' | sudo tee -a /etc/default/keyboard
  - echo 'BACKSPACE="guess"' | sudo tee -a /etc/default/keyboard
  - sudo apt-get install -y wine wine32 git wget xserver-xorg-video-dummy

setup:
  script:
    - mkdir -p ../dupe
    - cp -r * ../dupe
    - wget https://github.com/git-for-windows/build-extra/releases/download/git-sdk-1.0.3/git-sdk-installer-1.0.3-64.7z.exe
    - export DEBIAN_FRONTEND=noninteractive
    - wine git-*.exe -y -gm2
    - ls -lsah
